### ISSUE TITLE
error when run dssm

### ISSUE THREAD

**Issue by Kiris-tingna** [teinhonglo/Information-retrieval#2]
```
Traceback (most recent call last):
  File "G:/Kiristingna/nlp_segment_analyse/semantic/similarity/DSSM.py", line 123, in <module>
    dssm(data, y)
  File "G:/Kiristingna/nlp_segment_analyse/semantic/similarity/DSSM.py", line 99, in dssm
    relevant = Reshape((J + 1, 1))(_r)
  File "D:\Program Files (x86)\Python\lib\site-packages\keras\engine\topology.py", line 604, in __call__
    output_shape = self.compute_output_shape(input_shape)
  File "D:\Program Files (x86)\Python\lib\site-packages\keras\layers\core.py", line 385, in compute_output_shape
    input_shape[1:], self.target_shape)
  File "D:\Program Files (x86)\Python\lib\site-packages\keras\layers\core.py", line 379, in _fix_unknown_dimension
    raise ValueError(msg)
ValueError: total size of new array must be unchanged
```

**Comment by teinhonglo** [comment]
Hi!
Could you paste the  code segment of the "DSSM.py" and shape of data？
It seems to your input shape is variable, but input shape must be fixed in the same batch.

**Comment by Kiris-tingna** [comment]
this is my code
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
 @Time    : 2017/11/2 11:06
 @Author  : Kiristingna
 @File    : CDSSM.py
 @Software: PyCharm
"""
# An implementation of the Deep Semantic Similarity Model
import numpy as np

from keras.models import Model
from keras.layers import Dense, Convolution1D, Activation, Input, Reshape
from keras.layers.merge import concatenate, dot

def data_set(word_depth=10000, J=4):
    '''
    Build a random data set
    中文的输入层处理方式与英文有很大不同，首先中文分词是个让所有 NLP 从业者头疼的事情，即便业界号称能做到 95%左右的分词准确性，但分词结果极为不可控，往往会在分词阶段引入误差。
    所以这里我们不分词，而是仿照英文的处理方式，对应到中文的最小粒度就是单字了。
    由于常用的单字为 1.5 万左右，而常用的双字大约到百万级别了，所以这里出于向量空间的考虑，采用字向量（one-hot）作为输入，向量空间约为 1.5 万维。
    '''
    n_sample_size = 10
    l_querys = []
    query_length = 5

    pos_l_documets = []
    neg_l_documents = [[] for j in range(J)]

    doc_length = 100

    for i in range(n_sample_size):
        l_querys.append(np.random.rand(query_length, word_depth))
        pos_l_documets.append(np.random.rand(doc_length, word_depth))

    for i in range(n_sample_size):
        possibilities = list(range(n_sample_size))
        possibilities.remove(i)
        neg = np.random.choice(possibilities, J, replace=False)
        for j in range(J):
            negative = neg[j]
            neg_l_documents[j].append(pos_l_documets[negative])

    y = np.zeros((n_sample_size, J + 1))
    y[:, 0] = 1

    l_querys = np.array(l_querys)
    pos_l_documets = np.array(pos_l_documets)

    for j in range(J):
        neg_l_documents[j] = np.array(neg_l_documents[j])

    return [l_querys, pos_l_documets] + neg_l_documents, y


def dssm(data, y, word_depth=10000, max_pooling=300, semantic_feature=128, J=4, n_epoch=50):
    '''
    DSSM 的表示层采用 BOW（Bag of words）的方式，相当于把字向量的位置信息抛弃了，整个句子里的词都放在一个袋子里了，不分先后顺序
    :param semantic_feature: Dimensionality of latent semantic space
    :param window:
    :param J: Number of random unclicked documents serving as negative examples for a query.
    :return:
    '''
    # https://www.qcloud.com/community/article/226036

    # -------------- Q ------------------
    # query input and word hashing
    query = Input(shape=(None, word_depth), name='query')
    # 2 layer max pooling for nonlinear projection
    query_proj_1 = Dense(max_pooling, name="q_proj_1", activation="tanh")(query)
    query_proj_2 = Dense(max_pooling, name="q_proj_2", activation="tanh")(query_proj_1)
    # generate the semantic vector represenation of the query
    query_sem = Dense(semantic_feature, name="q_sem", activation="tanh")(query_proj_2)

    # --------------- D ---------------
    doc_proj_1 = Dense(max_pooling, name="d_proj_1", activation="tanh")
    doc_proj_2 = Dense(max_pooling, name="d_proj_2", activation="tanh")
    doc_sem = Dense(semantic_feature, name="d_sem", activation="tanh")

    # doc projection for pos
    pos_doc = Input(shape=(None, word_depth), name='pos_doc')
    pos_doc_proj_1 = doc_proj_1(pos_doc)
    pos_doc_proj_2 = doc_proj_2(pos_doc_proj_1)
    pos_doc_sem = doc_sem(pos_doc_proj_2)

    # doc projection for neg
    neg_docs = [Input(shape=(None, word_depth), name='neg_doc_'+str(j)) for j in range(J)]
    neg_doc_proj_1s = [doc_proj_1(neg_doc) for neg_doc in neg_docs]
    neg_doc_proj_2s = [doc_proj_2(neg_doc_proj_1) for neg_doc_proj_1 in neg_doc_proj_1s]
    neg_doc_sems = [doc_sem(neg_doc_proj_2) for neg_doc_proj_2 in neg_doc_proj_2s]

    # This layer calculates the cosine similarity between the semantic representations of
    Q_pos_cos = dot([query_sem, pos_doc_sem], axes=1, normalize=True, name="pos_cos")
    Q_neg_cos = [dot([query_sem, neg_doc_sem], axes=1, normalize=True, name="neg_cos_"+str(j)) for j, neg_doc_sem in enumerate(neg_doc_sems)]

    # contact cosine
    _r = concatenate([Q_pos_cos] + Q_neg_cos)
    relevant = Reshape((J + 1, 1))(_r)

    weight = np.array([1]).reshape(1, 1, 1)
    _gamma = Convolution1D(1, 1,
                           padding="same", input_shape=(J + 1, 1),
                           activation="linear", use_bias=False,
                           weights=[weight])(relevant)
    _gamma = Reshape((J + 1, ))(_gamma)
    out = Activation("softmax")(_gamma)

    model = Model(inputs=[query, pos_doc] + neg_docs, outputs=out)
    model.compile(optimizer="adadelta", loss="categorical_crossentropy", metrics=["accuracy"])
    model.summary()
    model.fit(data, y, epochs=n_epoch)


if __name__ == '__main__':
    # note1: word_deepth = window * total_letter_grams

    # load data
    data, y = data_set()

    dssm(data, y)
```

**Comment by Kiris-tingna** [comment]
@teinhonglo

**Comment by teinhonglo** [comment]
@Kiris-tingna 
It seems that you want to implement C-DSSM rather than DSSM.
There are a bits of difference between C-DSSM and DSSM. 
Instead of input of DSSM is BOW(bag of word, vocabulary size), input of CDSSM is word representation (word_length * word vector).

Quick implementation for C-DSSM:
https://github.com/teinhonglo/Information-retrieval/blob/master/Deep-Structured-Semantic-Models/dssm_cnn.py#L30

**Comment by Kiris-tingna** [comment]
`thanks a lot` @teinhonglo
